name: Run CI then push to Docker Hub

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - dev
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    # Pushes to master should build `min2ha/search-categories-api:master`, pushes to dev should build `min2ha/search-categories-api:dev`, pushes from forks should build e.g. `forker/ukwa-ui:master`.
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
